FROM ubuntu:latest


# Install some basic utilities
RUN apt update && apt upgrade -y && \
apt install vim wget curl git

# Install Miniconda and add it to the PATH
RUN mkdir -p ~/miniconda3 && \
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh && \
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 && \
rm -rf ~/miniconda3/miniconda.sh && \
~/miniconda3/bin/conda init bash && \
echo "export PATH=~/miniconda3/bin:$PATH" >> ~/.bashrc

# Update conda
RUN conda update --all

# Install Jupyter and JupyterLab
RUN conda install jupyter jupyterlab

# Create a new worspace directory
RUN ~/workspace && \
cd ~/workspace

EXPOSE 8080
EXPOSE 8888

CMD /bin/bash