FROM ubuntu:latest

RUN apt update && apt upgrade -y && \
apt install curl -y && \
apt install wget -y && \
apt install git -y && \
apt install vim -y && \
apt install python3 python3-pip -y && \
apt install nodejs npm -y && \
npm install -g firebase-tools && \
npm install -g n && \
npm update -g npm && \
n lts && \
curl https://sdk.cloud.google.com | bash && \
mkdir /repos

ENV PATH $PATH:/root/google-cloud-sdk/bin

EXPOSE 9005
EXPOSE 8080

CMD /bin/bash